

export const EXAMPLES = {

  ko: [
    ["cant tonight im so dead", "오늘은 못 가 개피곤해"],
    ["wait no way lmaooo", "헐 말도 안돼 ㅋㅋㅋㅋ"],
    ["ok see you tomorrow then", "ㅇㅋ 그럼 내일 봐"],
    ["omg thats so unfair", "헐 그거 개불공평해"],
    ["nah im good ill just stay in", "아냐 난 괜찮아 그냥 집에 있을래"],
    ["im so sorry i forgot lmao", "헐 미안 나 까먹었어 ㅋㅋ"],
    ["yo you free tonight? wanna vc", "야 오늘 밤 시간 돼? 통화할래?"],
    ["im gonna be in japan for 10 months", "나 일본에 10개월 있을 거야"],
    ["im going to bed now guys, do you guys sleep in the call", "나 이제 잔다 너네 통화 켜놓고 자?"],
    ["are you still in the call", "아직 통화 중이야?"],
    ["i just got home im gonna shower", "나 방금 집 왔어 샤워하려고"],

    ["youre so bad at this lol", "너 이거 개못한다 ㅋㅋ"],
    ["shut up lmao", "닥쳐 ㅋㅋㅋ"],
    ["i dont think so", "아닌 것 같은데"],
    ["i cant come", "나 못 가"],

    ["wait what", "잠깐 뭐?"],
    ["thats crazy", "헐 미쳤다"],
    ["im dying lmao", "아 개웃겨 ㅋㅋㅋㅋ"],
    ["thats rough", "헐 힘들겠다"],
    ["good for you", "오 잘됐다"],
    ["im so sad", "나 개슬퍼 ㅠㅠ"],
    ["i miss you", "보고싶어"],
    ["im bored", "심심해"],

    ["are you ok", "너 괜찮아?"],
    ["whats your favorite game", "너 무슨 게임 제일 좋아해?"],
    ["did you eat yet", "밥 먹었어?"],
    ["i cant hear you", "너 안 들려"],
    ["im down", "ㅇㅋ 나도"],
    ["im broke lol", "나 돈 없어 ㅋㅋ"],
    ["i never said that", "나 그런 말 한 적 없어"],

    ["thats mid", "그냥 그래"],
    ["no cap", "개진심"],
    ["lowkey agree", "좀 인정"],
    ["thats fire", "개쩐다"],
    ["hes so down bad", "걔 완전 빠졌어"],
    ["im deadass", "나 개진지해"],

    ["my grandma is in the hospital", "우리 할머니 병원에 계셔"],
    ["i lost my job", "나 일 잘렸어"],
    ["i failed the exam", "나 시험 떨어졌어"],
    ["im really sorry about earlier", "아까 일 진짜 미안해"],

    ["what are you doing", "뭐해?"],
    ["how was your day", "오늘 어땠어?"],
    ["can you send me that link", "그 링크 보내줄 수 있어?"],
    ["where are you", "어디야?"],
    ["how long does it take", "얼마나 걸려?"],
    ["do you want anything", "뭐 필요한 거 있어?"],

    ["thanks so much", "진짜 고마워"],
    ["no worries", "ㄱㅊㄱㅊ"],
    ["my bad", "미안 내 잘못"],
    ["hope you feel better", "빨리 나아 ㅠㅠ"],
    ["you got this", "너 할 수 있어 화이팅"],
    ["my mic is being weird", "내 마이크 좀 이상해"],
    ["my sister is visiting this weekend", "우리 언니 이번 주말에 와"],
    ["im smurfing", "나 부계로 하는 중"],
    ["lets run it back", "한 판 더 하자"],
    ["gg wp", "ㅈㅈ 수고"],
    ["hes feeding so hard", "쟤 개피딩해"],
    ["carry me pls", "나 좀 캐리해줘"],
    ["im grinding ranked", "랭겜 돌리는 중"],
    ["we got rolled", "우리 개털렸어"],
    ["hes cracked", "쟤 개잘해"],
    ["im cooked", "나 망했다"],
    ["thats sus", "그거 수상한데"],
    ["that goes hard", "그거 개쩐다"],
    ["bet", "ㅇㅋ 콜"],
    ["thats a W", "개이득"],
    ["im washed", "나 한물 갔어"],
    ["youre coping", "정신승리 하지마 ㅋㅋ"],
    ["anyone wanna play minecraft?", "야 마크 할 사람?"],
    ["wanna play valorant", "발로 할래?"],
    ["lets play league", "롤 하자"],
    ["anyone on roblox", "로블록스 하는 사람?"],
    ["im playing fortnite", "나 포트나이트 하는 중"],
    ["lets play overwatch", "옵치 하자"],
    ["anyone up for apex", "에이펙스 할 사람?"],
    ["wanna play deep rock galactic", "deep rock galactic 할래?"],
    ["raincheck?", "다음에 하자"],
    ["im queuing up", "큐 돌리는 중"],
    ["let me know", "알려줘"],
    ["dont tell anyone", "아무한테도 말하지마"],
  ],
  ja: [
    ["cant tonight im so dead", "今日は無理 まじ疲れた"],

    ["wait no way lmaooo", "えっ まじか草"],
    ["ok see you tomorrow then", "おけ じゃあ明日ね"],
    ["omg thats so unfair", "うわ それずるすぎ"],
    ["nah im good ill just stay in", "いや大丈夫 家にいるわ"],
    ["im so sorry i forgot lmao", "ごめん まじで忘れてた笑"],
    ["that was actually so funny lmao", "まじで面白かった草"],
    ["im so tired lol", "めっちゃ疲れた笑"],

    ["im going to bed now guys, do you guys sleep in the call", "もう寝るわ みんな通話つないだまま寝る？"],
    ["are you still in the call", "まだ通話入ってる？"],
    ["yo you free tonight? wanna vc", "今日ひま？ 通話する？"],

    ["im gonna be in japan for 10 months", "10ヶ月日本にいる予定"],
    ["i just got home im gonna shower", "今帰ってきた シャワー浴びる"],

    ["shut up lmao", "うるさい草"],
    ["youre so bad at this lol", "お前これ下手すぎ笑"],

    ["i dont think so", "そうは思わないけど"],
    ["i never said that", "そんなこと言ってないって"],

    ["wait what", "え、なに？"],
    ["thats crazy", "やばすぎ"],
    ["im dying lmao", "笑いすぎて死ぬ草"],
    ["thats rough", "それはきついな"],
    ["good for you", "よかったじゃん"],
    ["im so sad", "まじで悲しい"],
    ["i miss you", "会いたい"],
    ["im bored", "暇すぎ"],

    ["thats mid", "微妙"],
    ["no cap", "まじで"],
    ["lowkey agree", "ちょっとわかる"],
    ["thats fire", "やばい"],
    ["hes so down bad", "あいつガチ惚れしてる"],
    ["im deadass", "まじのまじ"],

    ["my grandma is in the hospital", "おばあちゃんが入院してる"],
    ["i lost my job", "仕事クビになった"],
    ["i failed the exam", "試験落ちた"],
    ["im really sorry about earlier", "さっきは本当にごめん"],

    ["what are you doing", "何してる？"],
    ["how was your day", "今日どうだった？"],
    ["can you unmute", "ミュート解除できる？"],
    ["how long does it take", "どのくらいかかる？"],
    ["do you want anything", "何かいる？"],
    ["im smurfing", "スマーフしてる"],
    ["lets run it back", "もう一回やろ"],
    ["gg wp", "お疲れ ナイスゲーム"],
    ["hes feeding so hard", "あいつ死にすぎ"],
    ["carry me pls", "キャリーして"],
    ["im grinding ranked", "ランク回してる"],
    ["we got rolled", "ボコボコにされた"],
    ["hes cracked", "あいつ強すぎ"],
    ["im cooked", "終わった"],
    ["thats sus", "それ怪しい"],
    ["that goes hard", "それやばい"],
    ["bet", "りょ"],
    ["thats a W", "勝ちだな"],
    ["im washed", "俺もう衰えた"],
    ["youre coping", "現実見ろ草"],
    ["lets play league", "LoL やろう"],
    ["anyone wanna play minecraft?", "マイクラやる人いる？"],
    ["wanna play deep rock galactic", "deep rock galactic やる？"],
    ["are you ok", "大丈夫？"],
    ["my mic is being weird", "マイク調子悪い"],
    ["im stressed about work", "仕事でストレス溜まってる"],
    ["raincheck?", "また今度"],
    ["im queuing up", "マッチ探してる"],
    ["let me know", "教えて"],
    ["dont tell anyone", "誰にも言わないで"],
  ],
  fr: [
    ["cant tonight im so dead", "je peux pas ce soir je suis mort"],
    ["wait no way lmaooo", "attends serieux mdrrr"],
    ["ok see you tomorrow then", "ok a demain alors"],
    ["omg thats so unfair", "putain c'est trop injuste"],
    ["nah im good ill just stay in", "nan ca va je vais rester chez moi"],
    ["im so sorry i forgot lmao", "desole j'ai completement oublie mdr"],
    ["yo you free tonight? wanna vc", "t'es dispo ce soir ? on s'appelle ?"],
    ["im gonna be in japan for 10 months", "je vais etre au japon pendant 10 mois"],
    ["im going to bed now guys, do you guys sleep in the call", "je vais dormir la vous dormez en vocal ?"],
    ["are you still in the call", "t'es encore en vocal ?"],
    ["i just got home im gonna shower", "je viens de rentrer je vais me doucher"],

    ["my bad", "ma faute"],
    ["shut up lmao", "ta gueule mdr"],
    ["youre so bad at this lol", "t'es trop nul a ca lol"],
    ["i dont think so", "je crois pas"],

    ["wait what", "attends quoi ?"],
    ["thats crazy", "c'est de ouf"],
    ["im dying lmao", "je suis mort de rire mdr"],
    ["thats rough", "ca craint"],
    ["good for you", "cool pour toi"],
    ["im so sad", "je suis trop triste"],
    ["i miss you", "tu me manques"],
    ["no way lmao", "serieux mdr"],

    ["thats mid", "c'est moyen"],
    ["no cap", "je te jure"],
    ["lowkey agree", "je suis un peu d'accord"],
    ["thats fire", "c'est ouf"],
    ["hes so down bad", "il est trop accro"],
    ["im deadass", "je suis serieux"],

    ["my grandma is in the hospital", "ma grand-mere est a l'hopital"],
    ["i lost my job", "j'ai perdu mon boulot"],
    ["i failed the exam", "j'ai rate l'examen"],
    ["im really sorry about earlier", "je suis vraiment desole pour tout a l'heure"],

    ["what are you doing", "tu fais quoi ?"],
    ["how was your day", "ta journee s'est bien passee ?"],
    ["how long does it take", "ca prend combien de temps ?"],
    ["do you want anything", "tu veux quelque chose ?"],
    ["im smurfing", "je smurf"],
    ["lets run it back", "on remet ca"],
    ["gg wp", "gg bien joue"],
    ["hes feeding so hard", "il feed a mort"],
    ["carry me pls", "carry moi stp"],
    ["im grinding ranked", "je farm la ranked"],
    ["we got rolled", "on s'est fait exploser"],
    ["hes cracked", "il est trop fort"],
    ["im cooked", "je suis foutu"],
    ["thats sus", "c'est louche"],
    ["that goes hard", "ca envoie"],
    ["bet", "ca marche"],
    ["thats a W", "c'est une win"],
    ["im washed", "j'ai chute"],
    ["youre coping", "t'accepte pas la defaite mdr"],
    ["anyone on roblox", "y'a quelqu'un sur roblox ?"],
    ["anyone wanna play minecraft?", "qui veut jouer a minecraft ?"],
    ["lets play league", "on joue a LoL ?"],
    ["let me know", "tiens moi au courant"],
    ["dont tell anyone", "le dis a personne"],
    ["im back", "je suis revenu"],
    ["raincheck?", "on remet a une autre fois ?"],
    ["im queuing up", "je lance une partie"],
  ],

  en: [
    ["오늘은 못 가 개피곤해", "cant tonight im so dead"],
    ["헐 말도 안돼 ㅋㅋㅋㅋ", "omg no way lmaooo"],
    ["今日は無理 まじ疲れた", "cant today im so tired"],
    ["je peux pas ce soir je suis mort", "cant tonight im dead"],

    ["おつかれ〜", "gg"],
    ["おつかれさま", "nice work"],
    ["それな", "facts"],
    ["りょ", "k"],
    ["まじ？", "for real?"],
    ["やば", "damn"],
    ["ドンマイ", "no worries"],
    ["ちょっと待って今行く", "wait a sec im coming"],
    ["寝落ちしてた", "i fell asleep"],
    ["全然大丈夫だよ", "its totally fine"],
    ["明日何時に集合？", "what time are we meeting tomorrow?"],
    ["いってきます", "heading out"],
    ["ただいま", "im home"],

    ["ㅇㅇ", "yeah"],
    ["ㄴㄴ", "nah"],
    ["ㅇㅋ", "ok"],
    ["ㄱㅅ", "thx"],
    ["헐 대박", "omg no way"],
    ["수고했어", "nice work"],
    ["잘자", "night"],
    ["화이팅", "you got this"],
    ["어디야?", "where are you?"],
    ["밥 먹었어?", "did you eat?"],
    ["나 지금 가", "im coming now"],

    ["ça va ?", "you good?"],
    ["à plus", "later"],
    ["de rien", "no worries"],
    ["t'inquiète", "dont worry about it"],
    ["nickel", "perfect"],
    ["ça marche", "sounds good"],
    ["grave", "for real"],
    ["je suis chaud", "im down"],

    ["on se capte demain", "lets catch up tomorrow"],
    ["j'ai grave la flemme", "i really cant be bothered"],
    ["ça me saoule", "its pissing me off"],
    ["j'en peux plus", "i cant anymore"],
    ["c'est chaud", "thats rough"],
    ["je suis dég", "im gutted"],

    ["ouais j'ai pas envie mec", "yeah i dont feel like it man"],

    ["ouais je sais pas mec c'est chelou", "yeah idk man thats weird"],
    ["je sais pas", "idk"],
    ["j'sais pas trop", "idk really"],
    ["je peux pas venir", "i cant come"],
    ["c'est pas grave", "its not a big deal"],
    ["j'ai rien fait", "i didnt do anything"],
    ["personne m'a dit", "nobody told me"],
    ["je comprends pas", "i dont get it"],

    ["개쩐다", "thats fire"],
    ["나 개진지해", "im deadass"],
    ["나 한물 갔어", "im washed"],
    ["정신승리 하지마 ㅋㅋ", "youre coping lmao"],
    ["걔 완전 빠졌어", "hes so down bad"],
    ["나 망했다", "im cooked"],
    ["그냥 그래", "its mid"],
    ["개이득", "thats a W"],
    ["ㅈㅈ 수고", "gg wp"],
    ["우리 개털렸어", "we got rolled"],
    ["쟤 개피딩해", "hes feeding so hard"],
    ["쟤 개잘해", "hes cracked"],
    ["나 못 가", "i cant come"],
    ["좀 늦을 것 같아", "i might be a bit late"],
    ["ごめん寝落ちした", "sorry i fell asleep"],
    ["無理かも", "i might not make it"],
    ["a demain", "see you tomorrow"],
    ["j'ai la flemme", "cant be bothered"],
    ["랭겜 돌리는 중", "im grinding ranked"],

    ["やばい", "thats crazy"],
    ["あいつ強すぎ", "hes cracked"],
    ["終わった", "im cooked"],
    ["現実見ろ草", "cope lmao"],
    ["微妙", "its mid"],
    ["勝ちだな", "thats a W"],
    ["俺もう衰えた", "im washed"],
    ["ボコボコにされた", "we got rolled"],
    ["あいつ死にすぎ", "hes feeding so hard"],
    ["りょ", "bet"],
    ["ランク回してる", "im grinding ranked"],

    ["ca envoie", "that goes hard"],
    ["il est trop fort", "hes cracked"],
    ["je suis foutu", "im cooked"],
    ["c'est louche", "thats sus"],
    ["c'est moyen", "its mid"],
    ["il feed a mort", "hes feeding so hard"],
    ["on remet ca", "lets run it back"],
    ["on s'est fait exploser", "we got rolled"],

    ["わかんない", "idk"],
    ["そんなこと言ってないって", "i never said that"],
    ["うるさい草", "shut up lmao"],

    ["merci beaucoup", "thanks so much"],
    ["ta gueule mdr", "shut up lmao"],
    ["ma faute", "my bad"],
    ["통화 켜놓고 자?", "do you sleep in the call?"],
    ["ㅇㅇ 나도 콜", "yeah im in"],
    ["콜", "im in"],
    ["ㄱㄱ", "lets go"],
    ["ㅅㄱ", "later"],
    ["ㅇㅈ", "facts"],
    ["인정", "facts"],
    ["ㄱㅊ", "its fine"],
    ["ㅂㅂ", "bye"],
    ["ㅊㅋ", "congrats"],
    ["ㅁㅊ", "thats crazy"],
    ["ㅎㅇ", "hey"],
    ["ㄱㅅ", "thx"],
    ["ㅈㅈ", "gg"],
    ["각 나왔다", "theres an opening"],
    ["실화냐", "is that for real"],
  ],
};
