const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("typeTranslate", {
  request: (request) => ipcRenderer.invoke("service:request", request),
  cancelRequest: (requestId) => ipcRenderer.invoke("service:cancel", requestId),
  restartService: () => ipcRenderer.invoke("service:restart"),
  getMeta: () => ipcRenderer.invoke("app:meta"),
  openData: () => ipcRenderer.invoke("app:open-data"),
  openExternal: (url) => ipcRenderer.invoke("app:open-external", url),
  copy: (text) => ipcRenderer.invoke("clipboard:write", text),
  getSecretStatus: () => ipcRenderer.invoke("secret:status"),
  saveSecret: (value) => ipcRenderer.invoke("secret:set", value),
  removeSecret: () => ipcRenderer.invoke("secret:remove"),
  getPreferences: () => ipcRenderer.invoke("app:preferences"),
  setTheme: (theme) => ipcRenderer.invoke("app:set-theme", theme),
  setStartup: (enabled) => ipcRenderer.invoke("app:set-startup", enabled),
  setOpenShortcut: (shortcut) => ipcRenderer.invoke("app:set-shortcut", shortcut),
  onTheme: (callback) => ipcRenderer.on("theme", (_, info) => callback(info)),
  minimize: () => ipcRenderer.send("window:minimize"),
  maximize: () => ipcRenderer.send("window:maximize"),
  hide: () => ipcRenderer.send("window:hide"),
  onNavigate: (callback) => ipcRenderer.on("navigate", (_, page) => callback(page)),
  onUpdate: (callback) => ipcRenderer.on("update", (_, info) => callback(info)),
  checkUpdates: () => ipcRenderer.invoke("app:check-updates"),
  installUpdate: () => ipcRenderer.invoke("app:install-update"),
});
